version: '2'

services:
  postgres:
    restart: always
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: WSPdBKxje8
    volumes:
      - ../django-postgres:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:4-alpine

  django:
    restart: always
    build: .
    environment:
      DB_PASSWORD: WSPdBKxje8
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - redis
      - postgres
